sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
- '8'
# - '7'
# - '6'
before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
install:
- npm install
script:
# - npm run lint
 - npm test
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run pack:linux; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run pack:osx; fi
# - npm run build
